CC=gcc
fmt_alpha: test_fmt_alpha.c
	$(CC) test_fmt_alpha.c libtpm.a -lm -o test_fmt_alpha_exe
fmt_d: test_fmt_d.c
	$(CC) test_fmt_d.c libtpm.a -lm -o test_fmt_d_exe
fmt_delta: test_fmt_delta.c
	$(CC) test_fmt_delta.c libtpm.a -lm -o test_fmt_delta_exe
fmt_h: test_fmt_h.c
	$(CC) test_fmt_h.c libtpm.a -lm -o test_fmt_h_exe
fmt_j: test_fmt_j.c
	$(CC) test_fmt_j.c libtpm.a -lm -o test_fmt_j_exe
fmt_ymd: test_fmt_ymd.c
	$(CC) test_fmt_ymd.c libtpm.a -lm -o test_fmt_ymd_exe
fmt_ymd_raw: test_fmt_ymd_raw.c
	$(CC) test_fmt_ymd_raw.c libtpm.a -lm -o test_fmt_ymd_raw_exe
d2d: test_d2d.c
	$(CC) test_d2d.c libtpm.a -lm -o test_d2d_exe
ymd2dd: test_ymd2dd.c
	$(CC) test_ymd2dd.c libtpm.a -lm -o test_ymd2dd_exe
ymd2y: test_ymd2y.c
	$(CC) test_ymd2y.c libtpm.a -lm -o test_ymd2y_exe
ymd2ymd: test_ymd2ymd.c
	$(CC) test_ymd2ymd.c libtpm.a -lm -o test_ymd2ymd_exe
m3Rx: test_m3Rx.c
	$(CC) test_m3Rx.c libtpm.a -lm -o test_m3Rx_exe
m3RxDot: test_m3RxDot.c
	$(CC) test_m3RxDot.c libtpm.a -lm -o test_m3RxDot_exe
m3m3: test_m3m3.c
	$(CC) test_m3m3.c libtpm.a -lm -o test_m3m3_exe
m6diff: test_m6diff.c
	$(CC) test_m6diff.c libtpm.a -lm -o test_m6diff_exe
m6inv: test_m6inv.c
	$(CC) test_m6inv.c libtpm.a -lm -o test_m6inv_exe
m6m6: test_m6m6.c
	$(CC) test_m6m6.c libtpm.a -lm -o test_m6m6_exe
m6scale: test_m6scale.c
	$(CC) test_m6scale.c libtpm.a -lm -o test_m6scale_exe
m6sum: test_m6sum.c
	$(CC) test_m6sum.c libtpm.a -lm -o test_m6sum_exe
m3v3: test_m3v3.c
	$(CC) test_m3v3.c libtpm.a -lm -o test_m3v3_exe
m6v3: test_m6v3.c
	$(CC) test_m6v3.c libtpm.a -lm -o test_m6v3_exe
v3c2s: test_v3c2s.c
	$(CC) test_v3c2s.c libtpm.a -lm -o test_v3c2s_exe
v3cross: test_v3cross.c
	$(CC) test_v3cross.c libtpm.a -lm -o test_v3cross_exe
v3unit: test_v3unit.c
	$(CC) test_v3unit.c libtpm.a -lm -o test_v3unit_exe
