CC=gcc
test_fmt_alpha: test_fmt_alpha.c
	$(CC) test_fmt_alpha.c libtpm.a -lm -o test_fmt_alpha
test_fmt_d: test_fmt_d.c
	$(CC) test_fmt_d.c libtpm.a -lm -o test_fmt_d
test_fmt_delta: test_fmt_delta.c
	$(CC) test_fmt_delta.c libtpm.a -lm -o test_fmt_delta
test_fmt_h: test_fmt_h.c
	$(CC) test_fmt_h.c libtpm.a -lm -o test_fmt_h
test_fmt_j: test_fmt_j.c
	$(CC) test_fmt_j.c libtpm.a -lm -o test_fmt_j
test_fmt_ymd: test_fmt_ymd.c
	$(CC) test_fmt_ymd.c libtpm.a -lm -o test_fmt_ymd
test_fmt_ymd_raw: test_fmt_ymd_raw.c
	$(CC) test_fmt_ymd_raw.c libtpm.a -lm -o test_fmt_ymd_raw
test_d2d: test_d2d.c
	$(CC) test_d2d.c libtpm.a -lm -o test_d2d
test_ymd2dd: test_ymd2dd.c
	$(CC) test_ymd2dd.c libtpm.a -lm -o test_ymd2dd
test_ymd2y: test_ymd2y.c
	$(CC) test_ymd2y.c libtpm.a -lm -o test_ymd2y
test_ymd2ymd: test_ymd2ymd.c
	$(CC) test_ymd2ymd.c libtpm.a -lm -o test_ymd2ymd
test_m3Rx: test_m3Rx.c
	$(CC) test_m3Rx.c libtpm.a -lm -o test_m3Rx
test_m3RxDot: test_m3RxDot.c
	$(CC) test_m3RxDot.c libtpm.a -lm -o test_m3RxDot
test_m3m3: test_m3m3.c
	$(CC) test_m3m3.c libtpm.a -lm -o test_m3m3
test_m6diff: test_m6diff.c
	$(CC) test_m6diff.c libtpm.a -lm -o test_m6diff
test_m6inv: test_m6inv.c
	$(CC) test_m6inv.c libtpm.a -lm -o test_m6inv
